animation/urls.py
from django.urls import path
from . import views

app_name = 'animation'
urlpatterns = [
    path('', views.TopicList.as_view(), name='animationthemes'),
    path('<int:topic_id>/', views.TopicDetails.as_view(), name='topicdetails'),
    path('Los-mejores-programas-de-animación-2D-GRATIS-2024/', views.SoftwareAnimationFree.as_view(), name='softwareanimationfree'),
    path('Los-mejores-programas-de-animación-2D-PAGO-2024/', views.SoftwareAnimationPay.as_view(), name='softwareanimationpay')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from todo.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('animation/', include(('animation.urls', 'animation'), namespace='animation'))
]

# Configuración para servir archivos estáticos durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

animation/models.py
import datetime
from django.db import models

# Create your models here.
class Topic(models.Model):
    title = models.CharField("Title", max_length=100)
    image = models.ImageField(upload_to="animation/images/")
    description = models.TextField("Description")
    date = models.DateField(default=datetime.date.today)
    
    def __str__(self):
        return self.title

todo/models.py
from django.db import models

# Create your models here.

animation/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Topic

# Create your views here.
class TopicList(View):
    def get(self, request, *args, **kwargs):
        topics = Topic.objects.all()
        context = {
            'topics': topics
        }
        return render(request, 'animationthemes.html', context)

class TopicDetails(View):
    def get(self, request, topic_id, *args, **kwargs):
        topic = get_object_or_404(Topic, pk=topic_id)
        context = {
            'topic': topic
        }
        return render(request, 'animationdetails.html', context)

class SoftwareAnimationFree(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'softwareanimationfree.html', context)
    
class SoftwareAnimationPay(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'softwareanimationpay.html', context)

todo/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.
class Home(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

animation/templates/animationdetails.html
{% extends "base.html" %} 
{% block content %}
<div class="text-center">
    <h2>{{ topic.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{topic.date|date:'F jS Y'}}</h3>
    <img src="{{ topic.image.url }}" alt='Image {{ topic.title }}' class="img-fluid">
    <div class="my-4">
        <p>{{ topic.description|safe }}</p>
    </div>

</div>
{% endblock %}

animation/templates/animationthemes.html
{% extends "base.html" %} 

{% block content %}
<h1>Temas de animación</h1>
{% for topic in topics %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{ topic.image.url }}" alt='Image {{ topic.title }}' class="img-fluid">
    
            </div>
            <div class="col-9">
                <h2>{{ topic.title }}</h2>
                <p>{{ topic.date|date:'M d Y'|upper }}</p>
                <p>{{ topic.description|striptags|truncatechars:200 }}</p>
                <br></br>
                <a href="{% url "blog:topic_details" topic.id %}" class="btn btn-primary">{{ topic.title }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

animation/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Animation</title>
</head>
<body>
    {% block content %}
    {% endblock %}  
</body>
</html>

animation/templates/softwareanimation.html
{% extends "base.html" %} 

{% block content %}
<h1>Los mejores programas de animación 2D GRATIS 2024</h1>
{% endblock %}

animation/templates/softwareanimationfree.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Los mejores programas de animación 2D GRATIS 2024</h1>
<p>Febrero 01, 2024 / Ing. Data Scientist Gerardo Hernández González</p>
<p>Tema que te puede interesar:</p>
<a href="{% url 'animation:softwareanimationpay' %}" target="_blank">Los mejores programas de animación 2D "PAGO" 2024</a>
<p></p>
<nav>
    <p>Contenido:</p>
    <ul>
        <li><a href="#pencil2d">Pencil2D</a>
            <ul>
                <li><a href="#pencil2d-caracteristicas">Características</a></li>
                <li><a href="#pencil2d-ventajas-desventajas">Ventajas y desventajas</a></li>
            </ul>
        </li>
        <li><a href="#krita">Krita</a>
            <ul>
                <li><a href="#krita-caracteristicas">Características</a></li>
                <li><a href="#krita-ventajas-desventajas">Ventajas y desventajas</a></li>
            </ul>
        </li>
        <li><a href="#blender">Blender</a>
            <ul>
                <li><a href="#blender-caracteristicas">Características</a></li>
                <li><a href="#blender-ventajas-desventajas">Ventajas y desventajas</a></li>
            </ul>
        </li>
        <li><a href="#opentoonz">OpenToonz</a> <!-- Completar -->
            <ul>
                <li><a href="#opentoonz-caracteristicas">Características</a></li>
                <li><a href="#opentoonz-ventajas-desventajas">Ventajas y desventajas</a></li>
            </ul>
        </li>
    </ul>
</nav>

<article>
    <section id="pencil2d">
        <!-- Contenido de Pencil2D -->
            <h2>Pencil2D</h2>
            <img src="https://www.pencil2d.org/images/pencil2d_horizontal_banner_1024x256_trans.png" alt="pencil2d" width="400px">
            <p>Al momento de buscar un software que nos permita crear un diseño sencillo y rápido para el usuario, si estás iniciando o ya cuentas con algo de experiencia en la animación, este programa será muy cómodo para utilizar.</p>
            <p><b>Página oficial para descargar Pencil2D:</b> <a href="https://www.pencil2d.org/download/" target="_blank">https://www.pencil2d.org/download/</a></p>
    </section>
    <section id="pencil2d-caracteristicas">
        <!-- Contenido de Características -->
        <h4>Características de Pencil2D</h4>
            <ul>
                <li>La herramienta es multiplataforma (<b>Windows, Mac OS, Linux y FreeBSD</b>).</li>
                <li>Admite gráficos de mapa de bits y vectoriales.</li>
                <img src="https://myk.graphics/wp-content/uploads/2023/08/diferencia-imagen-vectorial-bit-map.jpg" alt="vector y pixel map" width="300px">
                <p>Recomiendo la página: <a href="https://myk.graphics/imagen-vectorial-y-mapa-de-bits-comprendiendo-las-diferencias/" target="_blank">Imagen Vectorial y Mapa de Bits: Comprendiendo las Diferencias</a> by MYK, un diseñador UX/UI talentoso tiene otros temas interesantes en su blog.</p>
                <li>Puedes usar técnicas como: <b>"pieles de cebolla"</b> coloreadas para hacer más sencilla la animación, dando ese efecto de continuidad al objeto en movimiento.</li>
                <img src="https://images.squarespace-cdn.com/content/v1/59bdaa8264b05f47ee391660/1512050559672-BNSWG1WCMJW1SWJEZHZD/tarzan_arcs.png?format=1000w" alt="tarzan 'pieles de cebolla'" width="200px">
                <li>Exportar la animación resultante a <b>mp4, avi o gif animado</b>.</li>
            </ul>
    </section>
    <section id="pencil2d-ventajas-desventajas">
        <!-- Contenido de Ventajas y desventajas -->
        <h4>Ventajas y desventajas</h4>
            <ul>
                <b>Ventajas</b>
                <li>Fácil aprendizaje</li>
                <li>Multiplataforma, encuentras bastante información en tutoriales de Youtube y blogs de diferentes usuarios</li>
            </ul>
            <ul>
                <b>Desventajas</b>
                <li>Falta de herramientas más avanzadas para la implementación de movimiento y corrección.</li>
            </ul>
    </section>
</article>
<hr>
<article>
    <section id="krita">
        <h2>Krita</h2>
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/73/Calligrakrita-base.svg" alt="Krita logo" width="500px">
        <p>Es un programa muy versatil en su aprendizaje con un enfoque más profesional para la animación de código abierto, significa que sus licencias son de libre uso.</p>
        <p><b>Página oficial para descargar Krita:</b> <a href="https://krita.org/es/descargar/krita-desktop-es/" target="_blank">https://krita.org/es/descargar/krita-desktop-es/</a></p>
    </section>
    <section id="krita-carateristicas">
        <h4>Características de Krita</h4>
        <ul>
            <li>Multiplataforma (<b>Windows, Mac OS y Linux</b>).</li>
            <li>Máscaras de coloración y herencia alfa.</li>
            <img src="https://docs.krita.org/en/_images/Composition_animation.gif" alt="herencia alpha gif" width="300px">
            <li>Puedes importar paquetes para personalizar pinceles y agregar más paletas de colores a las que hay por defecto.</li>
            <li>Expansión de herramientas</li>
            <li>De igual manera que en Pencil2D, Krita cuenta con <b>imagen vectorial y mapeo de pixeles.</b></li>
            <li>También exportar la animación resultante a <b>png, jpg o gif animado</b>.</li>
        </ul>
    </section>
    <section id="krita-ventajas-desventajas">
        <h4>Ventajas y Desventajas</h4>
        <ul>
            <b>Ventajas</b>
            <li>Tiene exelente documentación, foros, tutoriales de habla inglesa y expañola.</li>
            <li>La curva de aprendizaje es moderada.</li>
        </ul>
        <ul>
            <b>Desventajas</b>
            <li>Carecen de funcionalidades al momento de editar imagenes con un rederizado alto, como lo podrían tener photoshop.</li>
        </ul>
    </section>
    <section id="krita-ventajas-desventajas">
        <h4>Ventajas y Desventajas</h4>
            <ul>
                <b>Ventajas</b>
                <li>Tiene exelente documentación, foros, tutoriales de habla inglesa y expañola.</li>
                <li>La curva de aprendizaje es moderada.</li>
            </ul>
            <ul>
                <b>Desventajas</b>
                <li>Carecen de funcionalidades al momento de editar imagenes con un rederizado alto, como lo podrían tener photoshop.</li>
            </ul>
    </section>
</article>
<hr>
<article>
    <section id="blender">
        <h2>Blender</h2>
        <img src="https://download.blender.org/branding/blender_logo.png" alt="blender logo" width="400px">
        <p>Blender es muy popular entre los usuarios que se dedican al modelado 2D y 3D ya sea de escenarios, elementos u objetos. Tiene bastantes años liderando como el software preferido por profesionales, creando una comunidad gigantesca, agregado características para que la experiencia en la creación de un proyecto muy satifactoría.</p>        
        <p><b>Página oficial para descargar Blender:</b> <a href="https://www.blender.org/download/" target="_blank">https://www.blender.org/download/</a></p>
    </section>
    <section id="blender-caracteristicas">
        <h4>Características</h4>
        <ul>
            <li>Multiplataforma (<b>Linux, macOS y Windows</b>)</li>
            <li>Se que animación 2D es el principal fuerte del programa, pero también la animación 3D es exelente, intercalando entre estás dos formas de diseño.</li>
            <li>Dentro encontraras una herramienta "motor interno de videojuegos", por si quieres llevar al siguiente nivel tus animaciones.</li>
            <li>Algo interesante en su página web donde podras ver toda su documentación, se encuentra una parte en español, lo cual facilitara las cosas cuando quieras implementar funciones muy especificas en tus modelados.</li>
        </ul>
    </section>
    <section id="blender-ventajas-desventajas">
        <h4>Ventajas y Desventajas</h4>
        <ul>
            <b>Ventajas</b>
            <li>Tiene exelente documentación y una grana comunidad que lo respalda.</li>
            <li>Gran variedad de opciones.</li>
            <li>Incluye su propio motor de videojuegos.</li>
        </ul>
        <ul>
            <b>Desventajas</b>
            <li>Puede ser complejo la configuración en un desarrollo muy especializado (sobre todo el 3D).</li>
            <li>La curva de aprendizaje puede ser más tartado que los anteriores programas, pero las habilidades desarrolladas se pueden polarizar a otros programas de animación muy fácil.</li>
        </ul>
    </section>
</article>
<hr>
<article>
    <section id="#opentoonz">
        <h2>OpenToonz</h2>
        <img src="https://freesvg.org/img/Opentoonz-1.png" alt="opentoonz logo" width="300px">
        <p>Es uno de los más famosos utilizado por el Studio Ghibli para crear sus trabajos durante muchos años.  Las primeras impresiones del programa resultan agradables y el aprendizaje es gradual como principiante</p>
        <p><b>Página oficial de descarga:</b> <a href="https://opentoonz.github.io/es/index.html">https://opentoonz.github.io/es/index.html</a></p>
        <img src="https://opentoonz.github.io/es/img/function_img01.png" alt="" width="500px">
    </section>
    <section id="#opentoonz-caracteristicas">
        <h4>Características</h4>
        <ul>
            <li>La mayoría de las funciones están para <b>Windows</b>. También soporta <b>Mac OS</b>, aunque no todas las herramientas.</li>
            <li>OpenToonz es un programa de código abierto, su código puede ser modificado y agregar mas funciones que tengan programas de pago.</li>

        </ul>
    </section>
    <section id="#opentoonz-ventajas-desventajas">
        <h4>Ventajas y desventajas</h4>
        <ul>
            <b>Ventajas</b>
            <li>Información en foros y tutoriales, para solucionar preguntas que tenga el ususario.</li>
            <li>Existen tutoriales profesionales tango en habla inglesa como española, para un aprendizaje optimo.</li>
        </ul>
        <ul>
            <b>Desventajas</b>
            <li>Solo se encuentran la mayoria de las funciones en Windows.</li>
            <li>Puede ser más complicado el aprendizaje que otros programas, pero la calidad de herramientas no hay comparación.</li>
        </ul>
    </section>
</article>
<footer>
    <p>&copy; 2024 Tu Sitio Web. Todos los derechos reservados.</p>
    <p>Contacto: info@tusitioweb.com</p>
    <a href="#" target="_blank">Facebook</a>
    <a href="#" target="_blank">Twitter</a>
    <a href="#" target="_blank">Instagram</a>
</footer>   
{% endblock %}

animation/templates/softwareanimationpay.html
{% extends "base.html" %} 

{% block content %}
<h1>Los mejores programas de animación 2D PAGO 2024</h1>
{% endblock %}

todo/templates/index.html
{% extends "layout.html" %} 
{% block content %}
<h1>Anime y animación</h1>
<hr>
<h2>Índice</h2>
<ul> 
    <a href="{% url "animation:animationthemes" %}"><li>Temas de anime</li></a>
    <ul>
        <ul>
            <li>~ Otros temas relacionados al anime ~</li>
            <a href="{% url "animation:softwareanimationfree" %}"><li>Los mejores programas de animación 2D "GRATIS" 2024</li></a>
            <a href="{% url "animation:softwareanimationpay" %}"><li>Los mejores programas de animación 2D "PAGO" 2024</li></a>
        </ul>
    </ul>
</ul>
{% endblock %}

todo/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Home</title>
</head>
<body>
    {% block content %}
    {% endblock %} 
</body>
</html>